// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnvgybcptlpgduktttdd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5udmd5YmNwdGxwZ2R1a3R0dGRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTEzMDgsImV4cCI6MjA2Nzc4NzMwOH0.B1q0W3tEFRiTXA2QWtdiD0qMhydPRBh_LbEMJHMt340";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});